//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DasBuildingWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DasBuilding_Com_CardInfo
    {
        public int CardID { get; set; }
        public string CardDispNo { get; set; }
        public string CardFixNo { get; set; }
        public Nullable<int> CardTypeID { get; set; }
        public Nullable<byte> CardStatus { get; set; }
        public Nullable<byte> CardIsUse { get; set; }
        public string CardCrtdBy { get; set; }
        public Nullable<System.DateTime> CardCrtdDay { get; set; }
        public string CardModiBy { get; set; }
        public Nullable<System.DateTime> CardModiDay { get; set; }
        public string IsUseSec0 { get; set; }
        public string IsUseSec1 { get; set; }
        public string IsUseSec2 { get; set; }
        public string IsUseSec3 { get; set; }
        public string IsUseSec4 { get; set; }
        public string IsUseSec5 { get; set; }
        public string IsUseSec6 { get; set; }
        public string IsUseSec7 { get; set; }
        public string IsUseSec8 { get; set; }
        public string IsUseSec9 { get; set; }
        public string IsUseSec10 { get; set; }
        public string IsUseSec11 { get; set; }
        public string IsUseSec12 { get; set; }
        public string IsUseSec13 { get; set; }
        public string IsUseSec14 { get; set; }
        public string IsUseSec15 { get; set; }
        public Nullable<decimal> MnySec0 { get; set; }
        public Nullable<decimal> MnySec1 { get; set; }
        public Nullable<decimal> MnySec2 { get; set; }
        public Nullable<decimal> MnySec3 { get; set; }
        public Nullable<decimal> MnySec4 { get; set; }
        public Nullable<decimal> MnySec5 { get; set; }
        public Nullable<decimal> MnySec6 { get; set; }
        public Nullable<decimal> MnySec7 { get; set; }
        public Nullable<decimal> MnySec8 { get; set; }
        public Nullable<decimal> MnySec9 { get; set; }
        public Nullable<decimal> MnySec10 { get; set; }
        public Nullable<decimal> MnySec11 { get; set; }
        public Nullable<decimal> MnySec12 { get; set; }
        public Nullable<decimal> MnySec13 { get; set; }
        public Nullable<decimal> MnySec14 { get; set; }
        public Nullable<decimal> MnySec15 { get; set; }
        public Nullable<int> TimesSec0 { get; set; }
        public Nullable<int> TimesSec1 { get; set; }
        public Nullable<int> TimesSec2 { get; set; }
        public Nullable<int> TimesSec3 { get; set; }
        public Nullable<int> TimesSec4 { get; set; }
        public Nullable<int> TimesSec5 { get; set; }
        public Nullable<int> TimesSec6 { get; set; }
        public Nullable<int> TimesSec7 { get; set; }
        public Nullable<int> TimesSec8 { get; set; }
        public Nullable<int> TimesSec9 { get; set; }
        public Nullable<int> TimesSec10 { get; set; }
        public Nullable<int> TimesSec11 { get; set; }
        public Nullable<int> TimesSec12 { get; set; }
        public Nullable<int> TimesSec13 { get; set; }
        public Nullable<int> TimesSec14 { get; set; }
        public Nullable<int> TimesSec15 { get; set; }
        public Nullable<int> CardSegID { get; set; }
    }
}
