//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DasBuildingWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DasBuilding_tenant
    {
        public int t_id { get; set; }
        public string t_name { get; set; }
        public string t_floor { get; set; }
        public string t_server_ip { get; set; }
        public string t_status { get; set; }
        public Nullable<System.DateTime> t_create_time { get; set; }
        public Nullable<System.DateTime> t_modify_time { get; set; }
    }
}
