//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DasBuildingWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class yida20171209NewEntities : DbContext
    {
        public yida20171209NewEntities()
            : base("name=yida20171209NewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DasBuilding_tenant> DasBuilding_tenant { get; set; }
        public virtual DbSet<DasBuilding_Com_EmpCard> DasBuilding_Com_EmpCard { get; set; }
        public virtual DbSet<DasBuilding_Com_CardInfo> DasBuilding_Com_CardInfo { get; set; }
    
        public virtual int DasBuilding_up_AutoMngCardID(Nullable<int> count, Nullable<int> cardSegID, Nullable<int> cardtypeid)
        {
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            var cardSegIDParameter = cardSegID.HasValue ?
                new ObjectParameter("CardSegID", cardSegID) :
                new ObjectParameter("CardSegID", typeof(int));
    
            var cardtypeidParameter = cardtypeid.HasValue ?
                new ObjectParameter("cardtypeid", cardtypeid) :
                new ObjectParameter("cardtypeid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DasBuilding_up_AutoMngCardID", countParameter, cardSegIDParameter, cardtypeidParameter);
        }
    }
}
